### PR TITLE
Feat/add segment/i928

### PR DESCRIPTION
**Pull request by beguene**
> [Download the latest build](https://github.com/hirosystems/stacks-wallet/actions/runs/1465883439)

Use the following template to create your pull request

## Description

This adds segment integration with all the main tracking event see #928 

## Type of Change
- [X ] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Testing information

Just use the wallet and the relevant event shall appear in the segment app console. 

## Checklist
- [X] Code is commented where needed
- [X] Unit test coverage for new or modified code paths
- [X] `npm run test` passes
- [ ] Changelog is updated
- [X] Tag 1 of @person1 or @person2

@kyranjamie @fbwoolf 
(Draft so we don't merge it into release)

### CODE REVIEW

**Comment by beguene** [comment]
@kyranjamie As per my testing SENTRY_DSN value is not "packaged" into the installer. Is Sentry working in production ?
We use webpack EnvironmentPlugin to achieve that but it does not seem to work (on the web-wallet it's working fine)
https://github.com/hirosystems/stacks-wallet/blob/feat/add-segment/I928/configs/webpack.config.base.js#L87

**Comment by kyranjamie** [comment]
@beguene just tried, it works. Have you set a DSN environment var when testing?

**Comment by beguene** [comment]
@kyranjamie I meant in the production build. Have you tried that ? There should be nothing to set if I understood correctly. It should be included into it.

**Comment by kyranjamie** [comment]
I've tested a production-like build, the real prod version we'll only know on release. Testing the debug build now, which is much the same as production.

```yaml
  - name: Build releases
    run: ./node_modules/.bin/cross-env yarn package-${{ matrix.NPM_COMMAND }}
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
       ....
```

dsn is bound here in CI

**Comment by beguene** [comment]
@kyranjamie Thanks for checking it out, I will see what's wrong with my setup.

**Comment by markmhx** [comment]
I'm reopening since it doesn't appear that we're getting virtually any production data into Segment:

image

It's strange that there are _some_ events though.

**Pull request merged**
